name: Release (Dry Run)
on:
  push:
    branches:
      - master

jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npx rollingversions publish --github-token ${{ secrets.GITHUB_TOKEN }} --dry-run